'use strict';

const test=require('node:test');const assert=require('node:assert/strict');const fs=require('fs');const os=require('os');const path=require('path');
const {WorkspaceStore}=require('../src/workspaceStore');const {HistoryStore}=require('../src/historyStore');const {decodeMapped}=require('../src/engineering');const {ModbusTcpStreamParser,decodeTcpAdu}=require('../src/modbus/tcpParser');const {TcpTransactionTracker}=require('../src/modbus/tcpTransactionTracker');const {buildRtuChannel,makeDeviceKey}=require('../src/transportIdentity');

function addRtu(s,p,port='COM7'){const c=buildRtuChannel({port,identity:{serialNumber:'TEST-ADAPTER'},config:{baudRate:9600,parity:'none',dataBits:8,stopBits:1}});s.upsertChannel(p.id,c);return c;}

test('workspace persists projects device names and register engineering maps',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'mbws-'));const file=path.join(dir,'w.json');let s=new WorkspaceStore({dataDir:dir,file});const p=s.getActiveProject(),c=addRtu(s,p);s.updateProject(p.id,{name:'Factory A'});const key=makeDeviceKey(c.channelId,7);s.setDevice(p.id,key,{name:'Inverter 07',manufacturer:'Test'});s.setRegister(p.id,{deviceKey:key,functionCode:3,address:100,name:'Power',type:'float32',byteOrder:'ABCD',scale:0.001,unit:'kW'});s=new WorkspaceStore({dataDir:dir,file});assert.equal(s.getActiveProject().name,'Factory A');assert.equal(s.getDevice(p.id,key).name,'Inverter 07');assert.equal(s.listRegisters(p.id,key)[0].unit,'kW');});

test('profiles can be created from one unit and applied to another on the same channel',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'mbpf-'));const s=new WorkspaceStore({dataDir:dir});const p=s.getActiveProject(),c=addRtu(s,p);const k1=makeDeviceKey(c.channelId,1),k2=makeDeviceKey(c.channelId,2);s.setDevice(p.id,k1,{manufacturer:'ACME',model:'X'});s.setRegister(p.id,{deviceKey:k1,functionCode:3,address:10,name:'V',type:'uint16',scale:0.1,unit:'V'});const profile=s.createProfileFromDevice(p.id,k1,{name:'ACME X'});const result=s.applyProfile(p.id,k2,profile.id);assert.equal(result.count,1);assert.equal(s.listRegisters(p.id,k2)[0].name,'V');assert.equal(s.getDevice(p.id,k2).model,'X');});

test('active discovery evidence persists with project but is not auto-bound to a device',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'mbdisc-'));const file=path.join(dir,'w.json');let s=new WorkspaceStore({dataDir:dir,file});const p=s.getActiveProject();const saved=s.saveDiscoveryRun(p.id,{jobId:'job-1',transport:'TCP',startedAt:100,completedAt:200,result:{transport:'TCP',host:'192.168.1.50',port:502,unitStart:1,unitEnd:2,results:[{unitId:1,responded:true,identificationSupported:true,objects:[{objectId:0,value:'ACME'}],identification:{vendorName:'ACME',modelName:'X1'}},{unitId:2,responded:false,identificationSupported:null,objects:[],identification:{}}]}});assert.equal(saved.summary.checked,2);assert.equal(saved.summary.identified,1);assert.equal(Object.keys(s.getActiveProject().devices).length,0);s=new WorkspaceStore({dataDir:dir,file});const runs=s.listDiscoveryRuns(p.id);assert.equal(runs.length,1);assert.equal(runs[0].target.host,'192.168.1.50');const full=s.getDiscoveryRun(p.id,runs[0].id);assert.equal(full.results[0].identification.vendorName,'ACME');assert.equal(s.listProjects()[0].discoveryRunCount,1);});

test('discovery evidence deletion does not modify device or register engineering data',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'mbdisc-del-'));const s=new WorkspaceStore({dataDir:dir});const p=s.getActiveProject(),c=addRtu(s,p),key=makeDeviceKey(c.channelId,3);s.setDevice(p.id,key,{name:'Meter'});const run=s.saveDiscoveryRun(p.id,{transport:'RTU',result:{transport:'RTU',port:'COM7',serial:{baudRate:9600},unitStart:3,unitEnd:3,results:[{unitId:3,responded:true,identificationSupported:false,objects:[]}]}});assert.equal(s.deleteDiscoveryRun(p.id,run.id),true);assert.equal(s.listDiscoveryRuns(p.id).length,0);assert.equal(s.getDevice(p.id,key).name,'Meter');});

test('engineering mapping combines adjacent words and scaling',()=>{const vals=new Map([['1:3:100',0x3f80],['1:3:101',0x0000]]);const out=decodeMapped({slaveId:1,functionCode:3,address:100,type:'float32',byteOrder:'ABCD',scale:10,offset:2,unit:'kW'},(s,f,a)=>vals.get(`${s}:${f}:${a}`));assert.equal(out.available,true);assert.equal(out.value,1);assert.equal(out.engineeringValue,12);});

test('history snapshots persist and query newest range',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'mbhist-'));const h=new HistoryStore({dataDir:dir});h.append('p1',{recordedAt:100,value:1});h.append('p1',{recordedAt:200,value:2});assert.deepEqual(h.query('p1',{since:150}).map(x=>x.value),[2]);});

test('Modbus TCP parser handles fragmented MBAP frames',()=>{const raw=Buffer.from([0,1,0,0,0,6,1,3,0,100,0,2]);const p=new ModbusTcpStreamParser();const seen=[];p.on('frame',f=>seen.push(f));p.push(raw.subarray(0,5));p.push(raw.subarray(5));assert.equal(seen.length,1);assert.equal(seen[0].transactionId,1);assert.equal(seen[0].decoded.unitId,1);assert.equal(seen[0].decoded.startAddress,100);assert.equal(seen[0].decoded.quantity,2);});

test('Modbus TCP transaction tracker pairs by transaction id and reconstructs registers',()=>{const req=decodeTcpAdu(Buffer.from([0,9,0,0,0,6,2,3,0,100,0,2]));const rsp=decodeTcpAdu(Buffer.from([0,9,0,0,0,7,2,3,4,0,10,0,20]));const t=new TcpTransactionTracker();t.request(req,1000);const tx=t.response(rsp,1040);assert.equal(tx.rttMs,40);assert.deepEqual(tx.decoded.registers.map(x=>x.address),[100,101]);assert.deepEqual(tx.decoded.registers.map(x=>x.value),[10,20]);});
