'use strict';

const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('fs');
const os=require('os');
const path=require('path');
const {PlatformRuntimeState}=require('../src/platformRuntimeState');
const {WorkspaceStore,WorkspaceCorruptionError}=require('../src/workspaceStore');
const {buildRtuChannel,buildTcpChannel,makeDeviceKey}=require('../src/transportIdentity');
const {AdvancedTransactionTracker}=require('../src/modbus/advancedTransactionTracker');

function responseTx(channel,unitId,value,address=100){return{direction:'RSP',transport:channel.transport,channel,decoded:{transport:channel.transport,slaveId:unitId,unitId,functionCode:3,functionName:'Read Holding Registers',registers:[{address,value}]},request:{transport:channel.transport,slaveId:unitId,unitId,functionCode:3,functionName:'Read Holding Registers',startAddress:address,quantity:1,timestamp:1000},rttMs:20};}

test('RTU channel stays stable across COM changes only when adapter identity is stable',()=>{const a=buildRtuChannel({port:'COM3',identity:{serialNumber:'ABC123'},config:{baudRate:9600}});const b=buildRtuChannel({port:'COM9',identity:{serialNumber:'ABC123'},config:{baudRate:9600}});assert.equal(a.channelId,b.channelId);const c=buildRtuChannel({port:'COM3',identity:{vendorId:'10C4',productId:'EA60'},config:{baudRate:9600}});const d=buildRtuChannel({port:'COM9',identity:{vendorId:'10C4',productId:'EA60'},config:{baudRate:9600}});assert.notEqual(c.channelId,d.channelId);});

test('TCP endpoints with the same Unit ID remain independent devices',()=>{const state=new PlatformRuntimeState();const a=buildTcpChannel({targetHost:'192.168.1.10',targetPort:502,mode:'proxy'});const b=buildTcpChannel({targetHost:'192.168.1.20',targetPort:502,mode:'proxy'});state.recordFrame(responseTx(a,1,111),1100,Buffer.from([1,3,2,0,111]));state.recordFrame(responseTx(b,1,222),1200,Buffer.from([1,3,2,0,222]));const regs=state.getRegisters({limit:20});assert.equal(regs.length,2);assert.equal(state.getRegisters({deviceKey:makeDeviceKey(a.channelId,1)})[0].lastValue,111);assert.equal(state.getRegisters({deviceKey:makeDeviceKey(b.channelId,1)})[0].lastValue,222);assert.throws(()=>state.getDevice(1),e=>e.code==='AMBIGUOUS_DEVICE');assert.equal(state.getDevice(makeDeviceKey(a.channelId,1)).summary.unitId,1);});

test('RTU and TCP with identical Unit/Slave/register numbers never merge',()=>{const state=new PlatformRuntimeState();const rtu=buildRtuChannel({port:'COM5',identity:{serialNumber:'RTU-A'},config:{baudRate:9600}});const tcp=buildTcpChannel({targetHost:'10.0.0.2',targetPort:502});state.recordFrame(responseTx(rtu,7,10,44112),1000,Buffer.from([7,3,2,0,10]));state.recordFrame(responseTx(tcp,7,20,44112),1100,Buffer.from([7,3,2,0,20]));assert.equal(state.getDevices().length,2);assert.deepEqual(state.getRegisters({limit:10}).map(r=>r.lastValue).sort((a,b)=>a-b),[10,20]);});

test('RTU broadcast address 0 is recorded as a request but never queued for timeout',()=>{const expired=[];const tracker=new AdvancedTransactionTracker({requestTimeoutMs:100,onTimeout:r=>expired.push(r)});const tx=tracker.process({transport:'RTU',slaveId:0,unitId:0,functionCode:6,functionName:'Write Single Register',kind:'ambiguous',address:10,value:1,matchToken:'10:1'},1000);assert.equal(tx.direction,'REQ');assert.equal(tx.broadcast,true);assert.equal(tx.noResponseExpected,true);assert.equal(tracker.pending.length,0);tracker.expire(5000);assert.equal(expired.length,0);});

test('TCP Unit ID 0 is not treated as an RTU broadcast',()=>{const tracker=new AdvancedTransactionTracker({requestTimeoutMs:100});tracker.process({transport:'TCP',slaveId:0,unitId:0,functionCode:3,functionName:'Read Holding Registers',kind:'request',startAddress:0,quantity:1},1000);assert.equal(tracker.pending.length,1);});

test('capture v2 preserves channel/device identity across reload',()=>{const state=new PlatformRuntimeState();const a=buildTcpChannel({targetHost:'192.168.50.10',targetPort:502});state.recordFrame(responseTx(a,3,333),1000,Buffer.from([3,3,2,1,77]));const cap=state.exportCapture();assert.equal(cap.schemaVersion,2);const next=new PlatformRuntimeState();next.loadCapture(cap);const key=makeDeviceKey(a.channelId,3);assert.equal(next.getRegisters({deviceKey:key})[0].lastValue,333);assert.equal(next.getChannels()[0].channelId,a.channelId);});

test('legacy capture is explicitly assigned to legacy channel with migration warning',()=>{const cap={format:'mbcap',version:1,transactions:[{timestamp:1000,direction:'RSP',transport:'RTU',slaveId:1,functionCode:3,functionName:'Read Holding Registers',decoded:{slaveId:1,functionCode:3,registers:[{address:1,value:9}]},request:{slaveId:1,functionCode:3,startAddress:1,quantity:1,timestamp:990},rttMs:10,byteLength:7,rawHex:'01'}]};const state=new PlatformRuntimeState();const status=state.loadCapture(cap);assert.equal(status.captureMigrationWarnings.length,1);assert.equal(state.getDevices()[0].channelId,'rtu:legacy');});

test('workspace v1 migration preserves old identity data as Legacy / Unassigned',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'mbmig-')),file=path.join(dir,'workspaces.json');fs.writeFileSync(file,JSON.stringify({version:1,activeProjectId:'p1',projects:[{id:'p1',name:'Old',site:'',bus:'Bus',description:'',createdAt:'2026-01-01',updatedAt:'2026-01-01',devices:{'1':{name:'Meter'}},registers:{'1:3:100':{slaveId:1,functionCode:3,address:100,name:'Power',type:'uint16',scale:1,offset:0,unit:'kW'}}}],profiles:[]}));const store=new WorkspaceStore({dataDir:dir,file});const p=store.getActiveProject();assert.equal(store.exportAll().version,2);assert.equal(Object.keys(p.devices).length,0);assert.equal(Object.keys(p.registers).length,0);assert.equal(Object.keys(p.legacyUnassigned.devices).length,1);assert.equal(Object.keys(p.legacyUnassigned.registers).length,1);assert.ok(store.getMigrationReport());assert.ok(fs.readdirSync(dir).some(x=>x.includes('v1-backup')));});

test('corrupt workspace is preserved and never silently replaced',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'mbbad-')),file=path.join(dir,'workspaces.json');fs.writeFileSync(file,'{"version":2,broken');assert.throws(()=>new WorkspaceStore({dataDir:dir,file}),e=>e instanceof WorkspaceCorruptionError&&e.code==='WORKSPACE_CORRUPT');assert.equal(fs.readFileSync(file,'utf8'),'{"version":2,broken');assert.ok(fs.readdirSync(dir).some(x=>x.includes('.corrupt-')));});
