'use strict';

module.exports = Object.freeze({
  protocol: require('./protocol'),
  ...require('./events'),
  ...require('./featureFlags'),
  ...require('./connectionBroker'),
  ...require('./connectionBrokerSafety'),
  ...require('./connectionCenterService'),
  ...require('./workbenchServer'),
  ...require('./workbenchServerV8'),
  ...require('./transports/virtualLoopback'),
  ...require('./transports/receiveQueue'),
  ...require('./transports/tcpStreamFramer'),
  ...require('./transports/networkAddresses'),
  ...require('./transports/tcpClientTransport'),
  ...require('./transports/tcpServerTransport'),
  ...require('./transports/serialFramers'),
  ...require('./transports/echoSuppressor'),
  ...require('./transports/serialTransport'),
  ...require('./transports/serialTransportSafety'),
  ...require('./master/asyncSemaphore'),
  ...require('./master/masterEngine'),
  ...require('./master/pollScheduler'),
  ...require('./master/writeSafety'),
  ...require('./master/addressNotation'),
  ...require('./master/masterWorkspaceService'),
  ...require('./master/masterWorkspaceRoutes'),
  ...require('./discovery/discoveryRequestEngine'),
  ...require('./discovery/discoveryScanService'),
  ...require('./discovery/discoveryRoutes'),
  ...require('./slave/virtualDevice'),
  ...require('./slave/virtualSlaveServer'),
  ...require('./slave/faultInjectionLab'),
  ...require('./slave/labVirtualSlaveServer'),
  ...require('./slave/dynamicValueEngine'),
  ...require('./slave/simulatorWorkspaceService'),
  ...require('./slave/simulatorRoutes'),
  ...require('./traffic/trafficTimelineService'),
  ...require('./traffic/registerLabService'),
  ...require('./traffic/trafficRoutes'),
  ...require('./project'),
});
