'use strict';

const {spawn}=require('child_process');const os=require('os');const path=require('path');const fs=require('fs');const ExcelJS=require('exceljs');
const port=19000+(process.pid%1000),dataDir=fs.mkdtempSync(path.join(os.tmpdir(),'modbus-v62-smoke-'));const child=spawn(process.execPath,['src/index-v6.js','--demo','--quiet','--web-port',String(port),'--data-dir',dataDir],{cwd:path.resolve(__dirname,'..'),stdio:'ignore'});
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function request(url,opt={},mode='auto'){const r=await fetch(`http://127.0.0.1:${port}${url}`,opt);const ct=r.headers.get('content-type')||'';let b;if(mode==='buffer')b=Buffer.from(await r.arrayBuffer());else if(ct.includes('json'))b=await r.json();else b=await r.text();if(!r.ok)throw new Error(`${url}: ${b?.error||b}`);return{body:b,headers:r.headers,status:r.status};}
async function get(url,opt){return(await request(url,opt)).body;}
(async()=>{try{let ok=false;for(let i=0;i<50;i++){try{await get('/api/status');ok=true;break;}catch{await sleep(200);}}if(!ok)throw new Error('v6.2 web server did not become ready');await sleep(1200);const status=await get('/api/status');if(!status.totals||status.totals.frames<1)throw new Error('demo generated no frames');if(!Array.isArray(status.channels)||!status.channels.length)throw new Error('channel-aware status unavailable');if(status.channels.some(c=>c.healthScore==null))throw new Error('per-channel health unavailable');const root=await get('/');if(!root.includes('UI v6.2')||!root.includes('platform-v6.js'))throw new Error('v6.2 UI assets were not injected');const config=await get('/api/config');if(config.version!=='6.2.0')throw new Error(`unexpected API version ${config.version}`);const ws=await get('/api/workspaces');if(!ws.activeProjectId||!ws.projects?.length)throw new Error('workspace API unavailable');const created=await get('/api/workspaces',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name:'Smoke Project',site:'Lab',bus:'Bus A'})});if(!created.id)throw new Error('project create failed');await get('/api/project/devices/1',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({name:'Meter 1',manufacturer:'Test'})});await get('/api/project/registers',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({slaveId:1,functionCode:3,address:100,name:'Test Value',type:'uint16',scale:0.1,unit:'V'})});const eng=await get('/api/engineering');if(!eng.some(x=>x.name==='Test Value'))throw new Error('engineering mapping API failed');const diag=await get('/api/diagnostics/deep');if(!Array.isArray(diag.findings))throw new Error('deep diagnostics unavailable');const tcp=await get('/api/tcp/status');if(tcp.mode!=='inline-proxy'||tcp.maxClientSessions<1)throw new Error('TCP subsystem unavailable');const analysis=await get('/api/analysis');if(analysis.healthAggregation!=='minimum-channel-score'||analysis.rates?.noiseScope!=='RTU-only')throw new Error('transport-specific health model unavailable');const report=await get('/api/report.html');if(!report.includes('Modbus Engineering Diagnostic Report'))throw new Error('HTML report generation failed');const manifest=await get('/api/export/manifest');if(manifest.version!=='6.2.0'||!manifest.exports?.some(x=>x.id==='xlsx')||!manifest.exports?.some(x=>x.id==='zip'))throw new Error('export manifest unavailable');
const xlsx=await request('/api/export/results.xlsx',{},'buffer');if(!xlsx.headers.get('content-type')?.includes('spreadsheetml')||xlsx.body.length<1000||xlsx.body.subarray(0,2).toString()!=='PK')throw new Error('XLSX export invalid');const wb=new ExcelJS.Workbook();await wb.xlsx.load(xlsx.body);for(const name of ['Summary','Devices','Polling Groups','Registers','Engineering Values','Timeouts','Exceptions','Traffic','Project History'])if(!wb.getWorksheet(name))throw new Error(`XLSX missing sheet: ${name}`);
const pdf=await request('/api/export/report.pdf',{},'buffer');if(!pdf.headers.get('content-type')?.includes('pdf')||pdf.body.length<500||pdf.body.subarray(0,4).toString()!=='%PDF')throw new Error('PDF export invalid');
const zip=await request('/api/export/project.zip',{},'buffer');if(!zip.headers.get('content-type')?.includes('zip')||zip.body.length<2000||zip.body.subarray(0,2).toString()!=='PK')throw new Error('ZIP backup invalid');
console.log(`V6.2 SMOKE PASS frames=${status.totals.frames} devices=${status.totals.devices} channels=${status.channels.length} xlsx=${xlsx.body.length} pdf=${pdf.body.length} zip=${zip.body.length}`);}finally{child.kill();setTimeout(()=>process.exit(0),50).unref();}})().catch(e=>{console.error(`V6.2 SMOKE FAIL: ${e.stack||e.message}`);child.kill();process.exitCode=1;});
