'use strict';

function parseArgs(argv) {
  const out={port:null,baudRate:9600,parity:'none',dataBits:8,stopBits:1,reconnectMs:2000,requestTimeoutMs:1000,mapFile:null,csvFile:null,raw:true,listPorts:false,quiet:false,autoRebind:true,webEnabled:true,webHost:'127.0.0.1',webPort:8080,confirmWebExternalBind:false,historyLimit:5000,demo:false,dataDir:'data',tcpProxy:false,tcpListenHost:'127.0.0.1',tcpListenPort:1502,tcpTargetHost:'127.0.0.1',tcpTargetPort:502};
  for(let i=0;i<argv.length;i++){const a=argv[i];const next=()=>{if(i+1>=argv.length)throw new Error(`Missing value after ${a}`);return argv[++i];};switch(a){case'--port':out.port=next();break;case'--baud':out.baudRate=Number(next());break;case'--parity':out.parity=next().toLowerCase();break;case'--data-bits':out.dataBits=Number(next());break;case'--stop-bits':out.stopBits=Number(next());break;case'--reconnect':out.reconnectMs=Number(next());break;case'--request-timeout':out.requestTimeoutMs=Number(next());break;case'--map':out.mapFile=next();break;case'--csv':out.csvFile=next();break;case'--no-raw':out.raw=false;break;case'--quiet':out.quiet=true;break;case'--list-ports':out.listPorts=true;break;case'--no-rebind':out.autoRebind=false;break;case'--no-web':out.webEnabled=false;break;case'--web-host':out.webHost=next();break;case'--web-port':out.webPort=Number(next());break;case'--confirm-web-external-bind':out.confirmWebExternalBind=true;break;case'--history':out.historyLimit=Number(next());break;case'--data-dir':out.dataDir=next();break;case'--demo':out.demo=true;break;case'--tcp-proxy':out.tcpProxy=true;break;case'--tcp-listen-host':out.tcpListenHost=next();break;case'--tcp-listen-port':out.tcpListenPort=Number(next());break;case'--tcp-target-host':out.tcpTargetHost=next();break;case'--tcp-target-port':out.tcpTargetPort=Number(next());break;case'--help':out.help=true;break;default:throw new Error(`Unknown argument: ${a}`);}}
  if(![5,6,7,8].includes(out.dataBits))throw new Error('data-bits must be 5, 6, 7, or 8');if(![1,2].includes(out.stopBits))throw new Error('stop-bits must be 1 or 2');if(!['none','even','odd','mark','space'].includes(out.parity))throw new Error('parity must be none/even/odd/mark/space');if(!Number.isFinite(out.baudRate)||out.baudRate<=0)throw new Error('baud must be positive');if(!Number.isFinite(out.reconnectMs)||out.reconnectMs<250)throw new Error('reconnect must be at least 250 ms');if(!Number.isFinite(out.requestTimeoutMs)||out.requestTimeoutMs<50||out.requestTimeoutMs>60000)throw new Error('request-timeout must be 50..60000 ms');for(const [name,p] of [['web-port',out.webPort],['tcp-listen-port',out.tcpListenPort],['tcp-target-port',out.tcpTargetPort]])if(!Number.isInteger(p)||p<1||p>65535)throw new Error(`${name} must be 1..65535`);if(!Number.isInteger(out.historyLimit)||out.historyLimit<100||out.historyLimit>100000)throw new Error('history must be 100..100000');return out;
}
function helpText(){return`\nModbus Engineering Tool 8.0.0\n\nUsage:\n  node src/index-v7.js [options]\n\nRTU options:\n  --list-ports\n  --port COM5\n  --baud 9600\n  --parity none\n  --data-bits 8\n  --stop-bits 1\n  --request-timeout 1000\n  --reconnect 2000\n  --no-rebind\n\nProject / capture:\n  --data-dir data\n  --map config/map.json\n  --csv capture.csv\n  --history 5000\n  --no-raw\n  --quiet\n\nWeb:\n  --web-host 127.0.0.1\n  --web-port 8080\n  --confirm-web-external-bind\n  --no-web\n  --demo\n\nModbus TCP inline analyzer proxy:\n  --tcp-proxy\n  --tcp-listen-host 127.0.0.1\n  --tcp-listen-port 1502\n  --tcp-target-host 192.168.1.50\n  --tcp-target-port 502\n\nThe TCP proxy forwards bytes unchanged while analyzing MBAP transactions. It is inline, not a passive packet tap.\n`;}
module.exports={parseArgs,helpText};
