'use strict';

function round(v,d=2){const m=10**d;return Math.round(Number(v||0)*m)/m;}
function analyzeDeep({state,config={}}){const status=state.getStatus(),analysis=state.getAnalysis(),devices=state.getDevices(),polls=state.getPollGroups(),tx=state.getTransactions({limit:20000});const findings=[];
  const unmatched=tx.filter(x=>x.direction==='RSP'&&!x.matched); if(unmatched.length)findings.push({severity:unmatched.length>5?'bad':'warn',code:'UNMATCHED_RESPONSES',title:'Unmatched responses observed',detail:`${unmatched.length} response frame(s) could not be paired with a request. Duplicate Slave IDs, missed request frames, or capture start mid-cycle are possible causes.`});
  const writes=tx.filter(x=>x.direction==='REQ'&&[5,6,15,16,22,23].includes(Number(x.functionCode))); if(writes.length)findings.push({severity:'info',code:'WRITES_OBSERVED',title:'Write traffic observed',detail:`${writes.length} write request(s) were observed. The sniffer did not generate them.`});
  const highJitter=polls.filter(p=>Number(p.jitterPct)>30&&p.requests>=5); if(highJitter.length)findings.push({severity:'warn',code:'HIGH_JITTER',title:'Unstable polling cadence',detail:`${highJitter.length} polling group(s) exceed 30% interval jitter.`});
  const timeoutDevices=devices.filter(d=>Number(d.timeouts)>0); if(timeoutDevices.length)findings.push({severity:'bad',code:'TIMEOUTS',title:'Missing responses detected',detail:`${timeoutDevices.length} device(s) have at least one request timeout.`});
  const potentialDuplicate=devices.filter(d=>d.unmatchedResponses>0||d.responses>d.requests+2); if(potentialDuplicate.length)findings.push({severity:'warn',code:'POSSIBLE_DUPLICATE_SLAVE',title:'Possible duplicate Slave ID / capture asymmetry',detail:`Slave(s) ${potentialDuplicate.map(d=>d.slaveId).join(', ')} show response behavior that deserves duplicate-address or capture-path verification.`});
  const baud=Number(config.baudRate||status.config?.baudRate||0),timeline=status.timeline||[];let utilizationPct=null;if(baud>0&&timeline.length){const bytes=timeline.slice(-60).reduce((a,b)=>a+Number(b.bytes||0),0),seconds=Math.max(1,Math.min(60,timeline.length)),bitsPerChar=11;utilizationPct=round((bytes*bitsPerChar/(baud*seconds))*100,2);if(utilizationPct>70)findings.push({severity:'bad',code:'BUS_UTILIZATION',title:'High estimated RTU utilization',detail:`Estimated serial occupancy is ${utilizationPct}% over the recent window.`});else if(utilizationPct>50)findings.push({severity:'warn',code:'BUS_UTILIZATION',title:'Elevated estimated RTU utilization',detail:`Estimated serial occupancy is ${utilizationPct}% over the recent window.`});}
  if(!findings.length)findings.push({severity:'good',code:'NO_MAJOR_ISSUES',title:'No major protocol anomaly detected',detail:'Current timeout, matching, jitter and utilization rules are within thresholds.'});
  return{generatedAt:Date.now(),healthScore:analysis.healthScore,rates:analysis.rates,utilizationPct,transport:state.getTransportSummary?.()||null,counts:{devices:devices.length,pollGroups:polls.length,transactions:tx.length,writes:writes.length,unmatched:unmatched.length,highJitter:highJitter.length},findings};
}
module.exports={analyzeDeep};
